### ISSUE TITLE
1.12 port

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/libVulpes#13]
Can I do a 1.12 port of this so that I can have a 1.12 version of AR out for until you get time to maintain one?

**Comment by zmaster587** [comment]
Sure, if it helps at all I can add a 1.12 branch to the repos

**Comment by dmodoomsirius** [comment]
Made a 1.12 branch on this repo as well as Advanced Rocketry.

**Comment by Thutmose** [comment]
closing this issue since the branch is now up and code compiles for 1.12.
