### ISSUE TITLE
[1.12] No recipes for Coils, Blocks, Etc

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/libVulpes#17]
the material coils, blocks, etc do not seem to have recipes, where are these added in the 1.10/1.11.2 versions, I cannot seem to find where the recipes are defined for them.

**Comment by zmaster587** [comment]
Should be fixed in the latest PR for AR from earlier today

**Comment by Thutmose** [comment]
yep, fixed in latest build of AR
