### ISSUE TITLE
Crash when opening previously generated worlds

### ISSUE THREAD

**Issue by comus777** [zmaster587/libVulpes#3]
I get this crash when I try to load up a previously existing world with libVulpes/Advanced Rocketry installed. New worlds are unaffected. 
[crash-2017-03-10_03.49.35-server.txt](https://github.com/zmaster587/libVulpes/files/832160/crash-2017-03-10_03.49.35-server.txt)
I'd try to figure out which one was really causing the problem but it's 4am and I'm sort of not in the mood to really spend 20 minutes booting up all those mods just to test if libVulpes is the culprit or if Advanced Rocketry is.

**Comment by zmaster587** [comment]
If you remove everything except AR and libvulpes does this still occur?

**Comment by comus777** [comment]
If I remove everything except those two the game will probably crash due to the sheer number of mods removed so I don't think that will get me anywhere.

**Comment by zmaster587** [comment]
Unless you're using reika's mods it should handle ok.  Easy way to make
sure it's not just the other mods you remove is to remove all the mods
other than the known working version on AR and libvulpes on a copy.  If
that doesn't crash, on another copy of the original world use the new
builds of AR and libvulpes.  If the first instance crashes and the 2nd one
doesn't then that's confirmation AR or libvulpes is the sole cause of the
problem.  If neither crash then there's some interaction between libvulpes
and AR and another mod

**Comment by comus777** [comment]
Yeah, I am actually using Reika's mods... 

I could try removing all mods but his, will give that a go I guess.

**Comment by comus777** [comment]
It works with my full modpack on the latest version. Well, it conflicts with Mystcraft in dimension IDs so I had to remove it (that mod causes me insane ticklag and is a general pain anyways so I don't use it) but it works fine now.
