### ISSUE TITLE
Needs a crafting recipe for IC2 plug

### ISSUE THREAD

**Issue by Peppernose145** [zmaster587/libVulpes#30]
I and my brother found the IC2 plug in the creative inventory, however when we attempted to get the crafting recipe, it became evident that there is no such recipe, meaning it is unobtainable in survival.

**Comment by zmaster587** [comment]
Are you using build 37 of Libvulpes?

**Comment by Peppernose145** [comment]
I am using build 37 of libVulpes.

IC2 version is 2.8.54-ex112

**Comment by zmaster587** [comment]
fixed
