### ISSUE TITLE
Server Crash When Using Holo-Projector

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/libVulpes#6]
Hello!

It looks like there's a server crash when the holo-projector is used. I'm not sure of your policy of Sponge servers are, but I wanted to pass this along just incase :) 

https://pastebin.com/xy3m2tHs

https://github.com/Darkosto/InvasionIssues/issues/74

MC: 1.10.2
Lib Vulpes: 0.2.0
Forge: 2254

Thank you :)
Darkosto

**Comment by zmaster587** [comment]
not quite sure how null is being passed to canInteractWithContainer, but I'll insert a null check
